### ISSUE TITLE
Serial port error with Windows 10

### ISSUE THREAD

**Issue by tlaukkan** [tlaukkan/zigbee4java#74]
I have seen serial port error today which suddenly manifested today on my windows 10 development workstation. Several reconnects of the dongle and reboot did not resolve this repeating issue on zigbee4java startup. It seemed to appear by chance and finally disappear similarly after a dongle reconnect. If anyone else is seeing this with genuine TI dongle then please report it here. There has been some changes in USB serial port implementation with windows 10 and this may require fixes with our serial port implementation.

C:\Users\tlaukkan\Development\projects\zigbee4java\zigbee-console-javase>java -jar target/zigbee-console-javase-2.0.3-SNAPSHOT.jar COM5 11 4951 false
ZigBee API starting up...10:01:23 442  INFO   Initialized ZigBee network with existing network state.
java.io.IOException: This port appears to have been shutdown or disconnected.10:01:23 495  ERROR  Exception inputStream reader parserThread
java.io.IOException: This port appears to have been shutdown or disconnected.
        at j.extensions.comm.SerialComm$SerialCommInputStream.read(SerialComm.java:512)
        at org.bubblecloud.zigbee.util.MarkableInputStream.read(MarkableInputStream.java:113)
        at org.bubblecloud.zigbee.network.packet.ZToolPacketParser.run(ZToolPacketParser.java:102)
        at java.lang.Thread.run(Unknown Source)
        at j.extensions.comm.SerialComm$SerialCommOutputStream.write(SerialComm.java:564)

**Comment by tlaukkan** [comment]
Does not seem to repeat anymore. Reopen if you experience this.
